#!/bin/bash
# /etc/init.d/ledblink
 
### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ledblink initscript
# Description: This service is used to manage a led
### END INIT INFO
 
case "$1" in
    start)
        echo "Starting mail"
        python /home/pi/mail.py &
        ;;
    stop)
        echo "Stopping mail"
        #killall ledblink.py
        kill $(ps aux | grep -m 1 'python /home/pi/mail.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service mail start|stop"
        exit 1
        ;;
esac
exit 0

